apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-backend
  namespace: hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-backend
  template:
    metadata:
      labels:
        app: hackathon-backend
    spec:
      containers:
      - name: hackathon-backend
        image: registry.fke.fptcloud.com/xplat-fke/be-hackathon:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_HOST
          value: "0.0.0.0"
        - name: FLASK_PORT
          value: "8080"
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: databasename
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: bucketName
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: accessKeyID
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: secretAccessKey
        - name: MINIO_HOST
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: endpoint
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 100Mi