apiVersion: v1
kind: Service
metadata:
  name: hackathon-backend
  namespace: hackathon
spec:
  selector:
    app: hackathon-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP