from environs import Env

env = Env()
env.read_env()

# Flask
FLASK_HOST = env("FLASK_HOST")
FLASK_PORT = env.int("FLASK_PORT")

ROOT_PATH_API = env("ROOT_PATH_API")

# DB
MYSQL_HOST = env("MYSQL_HOST")
MYSQL_PORT = env.int("MYSQL_PORT")
MYSQL_DB = env("MYSQL_DB")
MYSQL_USER = env("MYSQL_USER")
MYSQL_PASS = env("MYSQL_PASS")

# MINIO
MINIO_HOST = env("MINIO_HOST")
MINIO_PORT = env.int("MINIO_PORT")
MINIO_ACCESS_KEY = env("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = env("MINIO_SECRET_KEY")
MINIO_BUCKET_NAME = env("MINIO_BUCKET_NAME")

ALLOWED_EXTENSIONS = env("ALLOWED_EXTENSIONS")
